version: '2'
services:
  openldap:
    image: local/openldap:1.5.0
    container_name: openldap
    hostname: "ldap.example.org"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    networks:
      - cluster.local

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap
    networks:
      - cluster.local

  kerberos:
    image: local/kerberos:1.0.0
    hostname: "kerberos"
    container_name: "kerberos"
    environment:
      REALM: "EXAMPLE.ORG"
      DOMAIN_REALM: "example.org"
      KERB_MASTER_KEY: "masterkey"
      KERB_ADMIN_USER: "admin:"
      KERB_ADMIN_PASS: "admin"
      SEARCH_DOMAINS: "ldap.example.org"
      LDAP_DC: "dc=example,dc=org"
      LDAP_USER: "admin"
      LDAP_PASS: "admin"
      LDAP_URL: "ldaps://ldap.example.org"
      LDAP_CERTS: "/etc/openldap/certs/ca.crt"
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    volumes:
      - "shared-tmpfs:/tmp"
    depends_on:
      - openldap
      - phpldapadmin
    networks:
      - cluster.local

  zookeeper:
    image: "local/zookeeper:3.7"
    hostname: "zookeeper"
    container_name: "zookeeper"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - "zookeeper_data:/bitnami"
      - "shared-tmpfs:/tmp"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    depends_on:
      - openldap
      - kerberos
    networks:
      - cluster.local

  kafka:
    image: "local/kafka:2-debian-10"
    hostname: "kafka"
    container_name: "kafka"
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
      - "shared-tmpfs:/tmp"
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SASL_SSL
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
#      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_TLS_CLIENT_AUTH=none
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
#      - KAFKA_CERTIFICATE_PASSWORD="mypassword"
#      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD="mypassword"
#      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD="mypassword"
#      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=GSSAPI
#      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=GSSAPI
#      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://localhost:9092
    depends_on:
      - openldap
      - kerberos
      - zookeeper
    networks:
      - cluster.local

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  shared-tmpfs:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=2m,uid=1000"

networks:
  cluster.local:
    driver: bridge